### ISSUE TITLE
work with angular-cli?

### ISSUE THREAD

**Issue by fisherspy** [nrwl/webpack-plugin-critical#1]
angular-cli is now based on webpack, how can I use webpack-plugin-critical with angular-cli?

**Comment by jeffbcross** [comment]
The only way to get a hold of the webpack config from angular cli is to eject it, which means you're on your own for managing your build from that point forward. They plan to add an API for extending CLI in the future, at which point there could be an integration for a plugin like this.

If you __do__ want to eject and take control of your build, just run `ng eject` in your Angular CLI application. Then add Critical to the `webpack.config.js` it generates.
