### ISSUE TITLE
isn't possible to use this plugin when assets are placed inside subdirectories

### ISSUE THREAD

**Issue by borisirota** [nrwl/webpack-plugin-critical#2]
Hi, currently this plugin crashes when assets are placed inside subdirectories (`assets/css/*`, `assets/js/*`, etc.).

The issue is with the [webpack-util-cleantmp](https://github.com/jeffbcross/cleantmp) module which being used under the cover.

I submitted a [PR](https://github.com/jeffbcross/cleantmp/pull/1) to that module which fixes this issue 10 days ago and no response so far. Any ideas ?

I hope that it will be merged soon because in the meanwhile I'm not able to use this great plugin.

Thanks !

**Comment by jeffbcross** [comment]
Thanks for your PR! Merged and published that, so the correct version of cleantmp should be installed automatically for critical now, since it was just a patch release.
